spring.application.name=digital-wallet-system

# Server
server.port=8083

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/digital-wallet-system
spring.datasource.username=postgres
spring.datasource.password=postgres

# Entities
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Logging
logging.level.org.springframework=info
logging.level.com.example.digital_wallet_system=trace

# JWT
jwt.secret-key=${404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=3600000
